### ISSUE TITLE
Access the value of the initiationMethod

### ISSUE THREAD

**Issue by marktheunissen** [amazon-connect/amazon-connect-streams#441]
This commit introduces support for `initiationMethod`: https://github.com/amazon-connect/amazon-connect-streams/commit/fd7b3390d4680fca0f5df26de359890e99ca436b

However when we try read the value, it's always `null`, e.g.:
```js
const snapshot = contact.toSnapshot();
console.log(snapshot);
```
```yaml
contactData:
    attributes: {}
    connections: (2) [{…}, {…}]
....
    initialContactId: "abcdef......"
    initiationMethod: null
```

Is there another way to get the value? We would expect it to contain one of the values in the enum, e.g. 'callback', 'queue_transfer', etc.

Thanks!
